# Generated by Django 4.1.3 on 2022-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0004_orders_rename_sub_category_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
