# Generated by Django 4.1.3 on 2022-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0005_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
