# Generated by Django 4.1.3 on 2022-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0006_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders", name="amount", field=models.IntegerField(default=0),
        ),
    ]
