# Generated by Django 4.1.3 on 2022-12-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0007_alter_orders_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="phone",),
    ]
