# Generated by Django 4.1.3 on 2022-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0008_remove_orders_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders", name="cardno", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orders", name="cvv", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orders",
            name="expm",
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="year",
            field=models.CharField(max_length=111, null=True),
        ),
    ]
